### ISSUE TITLE
touch emulation(?)

### ISSUE THREAD

**Issue by marcin-biegun** [ChromeDevTools/EmulatedDeviceLab#62]
Hi, 
The nice thing about the standard device mode is an emulation of touch on click Can it be implemented in this plugin too?

**Comment by kdzwinel** [comment]
Hey stranger! We do emulate touch events: https://github.com/ChromeDevTools/EmulatedDeviceLab/blob/master/lib/device.js#L181 . You can test it here: http://www.snappymaria.com/canvas/TouchEventTest.html . 

<img width="555" alt="screen shot 2015-12-01 at 15 09 56" src="https://cloud.githubusercontent.com/assets/985504/11502868/9f1dff68-983d-11e5-82e3-154a1efe0077.png">

Do you have any specific example that doesn't work?

**Comment by marcin-biegun** [comment]
hm it seems it was something temporary on my end
strange things!
